### ISSUE TITLE
Make sure the user is able to update their Studio's map data when their RMXP maps has been modified

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#102]
As an **User**
I would like **Studio to be able to update my Studio's maps when my RMXP maps has been modifed**
So that **I can keep my project up to date**

### Acceptance criterias
- Make sure to check if the MapInfos.rxdata has been modified then propose an update to the maker by using the same way to update their maps than when a Tiled map has been modified.
- Make sure that feature is available only when `isTiledMode` is on `false` or `null`.

**Comment by NuriYuri** [comment]
Judging how complex is the RMXP Map Import I suggest that the user have to reload the project when there's any update on RMXP side.

The button can reload the project if it has been saved.

**Comment by AerunDev** [comment]
Yeah, make sense! We can do that. 👍
