### ISSUE TITLE
Node version consistency

### ISSUE THREAD

**Issue by BastienGauthier** [PokemonWorkshop/PokemonStudio#109]
See here : 
https://github.com/PokemonWorkshop/PokemonStudio/blob/d35eb00731e57516416f6e14ab474cc6fada1d24/.gitlab-ci.yml#L10

Node 18 is used, but node > 20.9 is requested in package.json

**Comment by NuriYuri** [comment]
Hi!

Thanks for spotting the issue. I made a PR (see links) and removed the incriminated file (since it's actually irrelevant to GitHub and we don't plan on supporting GitLab CI).

The PR also add configuration to ensure npm correctly complain when version does not match (it was not).
