### ISSUE TITLE
Rework the tooltips

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#115]
As a developer
I would like to rework the current tooltips
So that they are easier to use and there are no hover issues

## Context
*(From Yuri's researches)*
Following my little research in about Select I looked a little at the tooltips and in my opinion we should have a generalized simplification of the tooltips (to be tested) thanks to the popover (on the condition that the tooltips are never called on the 'element they inform).

For example:
```ts
let popoverEntity: HTMLElement | null = null;
const onMouseOver = (e: MouseEvent) => {
  const target = e.target;
  if (!(target instanceof HTMLElement) || target.offsetWidth >= target.scrollWidth) return;

  popoverEntity = target;
  const tooltip = document.getElementById('super-tooltip');
  if (tooltip) {
    const clientPos = target.getBoundingClientRect();
    tooltip.innerText = target.innerText;
    tooltip.style.top = `${clientPos.top}px`;
    tooltip.style.left = `${clientPos.right}px`;
    tooltip.showPopover();
  }
};
const onMouseOut = (e: MouseEvent) => {
  if (!(e.target instanceof HTMLElement) || e.target !== popoverEntity) return;

  const tooltip = document.getElementById('super-tooltip');
  if (tooltip) {
    tooltip.innerText = '';
    tooltip.hidePopover();
  }
  popoverEntity = null;
};
```

And an example of the code usage:
```ts
  useEffect(() => {
    window.addEventListener('mouseover', onMouseOver, { capture: true, passive: true });
    window.addEventListener('mouseout', onMouseOut, { capture: true, passive: true });
    return () => {
      window.removeEventListener('mouseover', onMouseOver);
      window.removeEventListener('mouseout', onMouseOut);
    };
  }, []);
```

And in `index.html`:
```html
<div id="super-tooltip" popover="manual" style="margin: 0"></div>
```

See the documentation:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover
- https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/ffb80837-184f-404f-9370-e93f24d7ca66

**Comment by NuriYuri** [comment]
Done in PokémonStudio project
