### ISSUE TITLE
Make sure that the user can use the Showdown import even if there is no trainer in the database

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#145]
As a User
I would like to use the Showdown Import to import Pokémon even if there is no trainer in the database
So that I can use it on the first trainer or group

Related to #32 
**Really not a priority because this is a bug only if you have no trainer in the database**

**Comment by Zodiarche** [comment]
Est-ce qu'il est vraiment possible d'avoir aucun trainer actuellement ?

Quand il nous reste un seul trainer on ne peut pas le supprimer : 
![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/81259986/759ebfaf-7739-4ff3-90f5-ea2d21b584aa)

Et si on le supprime manuellement on ne peut plus ouvrir notre projet :
![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/81259986/65e8b610-4cda-4ff0-97c9-a377e8a4ff0e)

**Comment by Zodiarche** [comment]
Ce qui peut être pertinent par contre, c'est de débloquer l'import et uniquement en showdown si on n'a qu'un seul trainer.
