### ISSUE TITLE
Fix the new text file name placeholder

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#182]
## Context
When you create a new text file, the name input placeholder is the wrong one.

![Image](https://github.com/PokemonWorkshop/PokemonStudio/assets/20935418/f656ba63-5593-404e-b7e7-e1b6fd3813b5)

## Steps to reproduce
- Load a project
- Go to the Texts page
- Create a new Text file
- Check the Name input placeholder

**Comment by Palbolsky** [comment]
The problem is in the i18n files (text_management.json), in the `example_name` attribute.
