### ISSUE TITLE
Add a placeholder to make sure the user knows how to get started with the Map management UI

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#186]
As an User
I would like to know what I have to do when I land on the Map UI in Tiled mode with no maps
So that I'm able to know how to get started with this UI, depending on my project progress

## Proposition
For the Tiled users, the version 2 leads to an empty map management UI, with no maps. It should be useful to add en Empty state to guide the users.

[See the design on Figma](https://www.figma.com/file/xglOHHLb96zfPMTXd3v8i9/Pok%C3%A9mon-Studio?type=design&node-id=10592-12209&mode=design&t=1Yyivnu3flKnJP8b-4)

**Comment by Palbolsky** [comment]
Si j'ai un design sur Figma je te fais ça demain :)
