### ISSUE TITLE
Make sure the Select follows the cursor when the user uses TOP/DOWN arrows

### ISSUE THREAD

**Issue by PokemonWorkshop** [PokemonWorkshop/PokemonStudio#25]
As a **User**
I would like **the Select follows the curser when I press TOP DOWN arrows keys**
So that **I can use my keyboard to navigate through the select**

> [!NOTE]
> We can also investigate about the Selects that stay opened if you're activating another Select

**Comment by AerunDev** [comment]
Cancelled and managed in the #113
