### ISSUE TITLE
Studio can't open Tiled on Linux

### ISSUE THREAD

**Issue by Palbolsky** [PokemonWorkshop/PokemonStudio#260]
### Description

Studio can't open Tiled on Linux. There are no errors.

### Anything else

https://discord.com/channels/143824995867557888/1217200620516147231

**Comment by AerunDev** [comment]
I've removed this story from the Sprint 18.
An issue has been opened on Tiled's GitHub to make sure we're able to fix it on our side: https://github.com/mapeditor/tiled/issues/3914
This fix will be available on the next Tiled 1.11 version.
