### ISSUE TITLE
Implement the Game Options part of the Project Settings

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#262]
As a User
I would like to update my Game Options related settings
So that I can select them from Studio

## Where to find the components that can be reused
- The dex Pokémon list: `src\views\pages\database\Dex\Dex.page.tsx` & `src\views\components\database\dex\DexPokemonList.tsx`

[See the Design on Figma](https://www.figma.com/file/xglOHHLb96zfPMTXd3v8i9/Pok%C3%A9mon-Studio?type=design&node-id=7010-8976&mode=design&t=c61L2M4nUwmodmpE-4)

**Comment by Zodiarche** [comment]
Salut, je ne vais pas avoir le temps de m'occuper de cette tâche encore pendant un très long moment, si quelqu'un veut la prendre il peut. Merci.
