### ISSUE TITLE
Blurr the text of a text input if the user scroll on a virtualized list and lose the focus

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#309]
As a User
I would like to keep my text saved if I scroll in a virtualized list and my text input focus is lose
So that I don't lose my text typed

**Comment by Zodiarche** [comment]
Le comportement est bizarre, je ne pense pas qu'on doit changer le comportement du onBlur mais plutôt ajouter un évènement sur le scroll, ça peut être plus complexe que ce que je pense
