### ISSUE TITLE
Allow the user to manage a custom environment (#294) v2

### ISSUE THREAD

**Issue by andykimpe** [PokemonWorkshop/PokemonStudio#312]
palb did it here in your commit

palb makes you here in your commit

add lines of text in English and French

but you didn’t include them in other languages

https://github.com/PokemonWorkshop/PokemonStudio/commit/2ca91441534ec0760c12583cfe9fd2b997682f64

when you work on multi-language
never add text in a language
without it being reported in all languages
that you chose to use in your program
so fake add the lines and translate them like this

the language is missing

German, Spanish, Italian, Portuguese

[Compare](https://github.com/andykimpe/PokemonStudio/compare/294e13fb08d30036f07001c75934ee201307c891...andykimpe:PokemonStudio:02f2596f743a64ae2468a6e36fbeb866066ae933)     
      
https://github.com/andykimpe/PokemonStudio/compare/294e13fb08d30036f07001c75934ee201307c891...andykimpe:PokemonStudio:02f2596f743a64ae2468a6e36fbeb866066ae933.patch     
          
            
         
  
        
       
         
       
https://context.reverso.net/translation/english-german/Custom

https://context.reverso.net/translation/english-german/Custom+environment

https://context.reverso.net/translation/english-german/Invalid+format

https://context.reverso.net/translation/english-spanish/Custom

https://context.reverso.net/translation/english-spanish/Custom+environment

https://context.reverso.net/translation/english-spanish/Invalid+format

https://context.reverso.net/translation/english-italian/Custom

https://context.reverso.net/translation/english-italian/Custom+environment

https://context.reverso.net/translation/english-italian/Invalid+format

https://context.reverso.net/translation/english-portuguese/Custom

https://context.reverso.net/translation/english-portuguese/Custom+environment

https://context.reverso.net/translation/english-portuguese/Invalid+format

either you translate as his
either you put the variables back in English
but variables should always be carried forward
in all languages
otherwise its can create problems
in the relevant programme

**Comment by Palbolsky** [comment]
These languages are deliberately omitted as our team is comprised of people only fluent in both English and French.

Our translation policy is to translate only into English and French as we are able to furnish a hand-made translation, not a machine-provided one. Other people who are asked to do so from time to time (or who come to us) translate the missing texts.

The absence of translation does not cause any bugs; English is used by default if a translation is missing.

**Comment by pw-rey** [comment]
I'll also add that we're currently doing some background work to benchmark different ways to setup a crowdsourcing for the translations, as stated in both #48 and #300, to make it easier for contributors to help in adding new languages to the software.
