### ISSUE TITLE
Typing in an input should not trigger the CTRL LEFT / RIGHT shortcuts

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#337]
As a User
I would like Studio to not trigger the CTRL LEFT / RIGHT shortcuts when I'm typing in a Text Input
So that CTRL + SHIFT + LEFT / RIGHT wont trigger them and break my flow

## Steps to reproduce
- GIVEN that I've loaded a project,
- THEN gone to the Texts management UI,
- WHEN I'm editing a text entry in the list,
- AND I'm using the CTRL LEFT / RIGHT shortcuts
- THEN Studio will navigate to the previous or next CSV instead

## Expected behaviour
- GIVEN that I've loaded a project,
- THEN gone to the Texts management UI,
- WHEN I'm editing a text entry in the list,
- AND I'm using the CTRL LEFT / RIGHT shortcuts
- THEN my cursor should go to the previous / next word
See the reaction by using Notepad, this is a basic typing shortcut.

**Comment by Zodiarche** [comment]
Dans quel genre d'input parce que j'ai essayé et je n'ai pas réussi à reproduire ce bug.

**Comment by Menthx** [comment]
Hum, ça n'a pas l'air d'etre sur toute les pages, j'ai reproduit uniquement sur la page des groupes sur des champs de nombres..

https://github.com/PokemonWorkshop/PokemonStudio/assets/36339268/3a44b049-f45e-4d12-8e02-f13383940c4a

**Comment by Palbolsky** [comment]
C'est parce que cette page n'a pas eu la refonte, comme les quêtes. Donc ça me semble pas pertinent de prendre du temps pour corriger, ça se corrigera tout seul lors de la refonte.
