### ISSUE TITLE
Unable to Remove Ability from Pokemon after adding

### ISSUE THREAD

**Issue by aten2049** [PokemonWorkshop/PokemonStudio#394]
### Description

I am unable to remove a pokemon's ability in the database screen after selecting one. I placed an ability in slot 2 and then wanted to remove it, but there was no way to do so. Removing the text and either clicking out or pressing "enter" simply reverted it to what it previously was. I had to delete the pokemon and re-make it.

### Current Behavior:

You select abilities by clicking on the abilities section. They are blank at first, but you can fill them.

### Expected Behavior:

There would be an option for either no ability or a clear option for the specific ability section. Or if you remove the ability name and click enter that would also clear it.

**Comment by AerunDev** [comment]
This is the expected behavior. In the PSDK code, a creature must always have an ability. If the creature has only one ability, it should be repeated three times.

Allowing the abilities to be removed wouldn't make sense.
