### ISSUE TITLE
The user would like their moves to be able to inflict custom statuses

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#41]
## Description
As a User
I would like my moves to be able to inflict custom statuses
So that I can set custom moves easily
So that I can use my custom statuses

> [!NOTE]
> Check the SystemTags related code to use the "Custom_xxxx" logic.

## Testing cases
- When you're on a move's database page,
- And you're editing the status the move can inflict,
- Then you can set the status on "Custom",
- Then a new Text Input appears,
- Then you can write the Identifier of your custom status in this Text Input.

> [!NOTE]
> Check the move's function data edition (battle engine method) with the custom entry.
> Also check the Group environment custom entry.

**Comment by Palbolsky** [comment]
Un exemple avec les systemtags (fichier group.ts) : 

![Image](https://github.com/user-attachments/assets/4758a4ef-42c5-4576-a2d0-0255d908835b)
