### ISSUE TITLE
Make a Weblate analysis and see if we can use it for Studio once it is Open Source

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#48]
As a member of the dev team
I would like to know if we can setup the Studio's app texts on Weblate
So that we can make the app texts localization easier for the community

**Comment by NuriYuri** [comment]
Weblate n'est pas gratuit. C'est minimum 17€ / mois (sans réduction en payant par anuité). L'offre auto-hébergée pourrait être intéressante mais elle ne l'est pas pour plusieurs raisons:

1. Ca met de la charge de notre coté et déjà qu'on galère à développer Studio si on se retrouve avec de la charge pour ça c'est compliqué.
2. "Weblate est plus facile à installer en utilisant pip ou Docker": On ne peut pas utiliser docker sur notre hébergement. Et python = gros stop parce que faire du python sans être un pro c'est le meilleur moyen de te faire hacker. (Y'a des tonnes de virus qui passent par pip)
3. Weblate a l'air spécialement orienté développeur. Ils ont peut-être une UI sympathique mais quand tu vas sur une page de téléchargement et qu'on te propose le code source en tant que CTA primaire c'est trash. Imagine si tu dois compiler NodeJS et Git par le code source.

Je vais chercher des alternatives autre qu'utiliser Studio lui même pour ça.

**Comment by NuriYuri** [comment]
Quelques alternatives:

- https://crowdin.com/pricing#crowdin-pricing-key-features (ça parle de hosted words c'est pas très clair si c'est juste un mot ou une ligne complète)
- https://pontoon.mozilla.org aucune idée de si c'est payant gratuit ou quoi que ce soit ça te dis direct "commence à traduire". On peut utiliser ça en dernier recours si besoin.
- http://zanata.org ça a l'air obscur mais à tester.

C'est tout ce que j'ai trouvé, les trois quart du temps c'est payant.

**Comment by NuriYuri** [comment]
Par pur hasard je suis tombé sur ça: https://github.com/ever-co/ever-traduora

C'est codé en typescript / React (donc notre stack) et c'est open source. On peut host du nodejs à priori donc faudra que je fasse une évaluation.
