### ISSUE TITLE
The user would like to go to the languages settings UI right from the Texts UI to manage them easily

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#67]
As an **User**
I would like **to go to the languages settings UI right from the Texts UI**
So that **I can manage them easily**

## Acceptance criterias
- [ ] The button in the Texts UI ControlBar leads to the languages settings UI

**Comment by NuriYuri** [comment]
I can't find the design for the language settings UI

**Comment by Palbolsky** [comment]
> I can't find the design for the language settings UI

Il faut réactiver ce bouton :
![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/7809685/cdb6c838-a3c6-4100-8f18-b559f7c58d52)

En cliquant dessus on doit se rendre sur la page des langues du projet.

**Comment by NuriYuri** [comment]
I got confused with the app language settings x) (Language issues + missing screenshot/missing links to figma designs)
